### ISSUE TITLE
편의성 개선안

### ISSUE THREAD

**Issue by AnnyangEH** [Kdelphinus/Yacht_Dice#2]
1. 게임 재시작시동일한 플레이어 이름으로 유지할지, 다시 진행할지 선택할 수 있는 메시지
2. 특정상황(야추, 스트레이트, 포오브카인드, 풀하우스) 등 현재 등록되지 않은 점수에 대해서 메시지 출력
3. 킵할 주사위를 여러개씩 선택할 수 있게, ex)123 은 1번 2번 3번 주사위 킵
4. 새로 굴린 주사위에 대한 시각화, 같은 자리 같은 수가 나올 시 혼선이 있으니 >> 색상 또는 모형의 변화로 새로운 눈금임을 표시
5. 승리한 player에 대한 축하메시지 확대, 강화, 문구 추가
6. 8. 4 of a kind 라서 헷갈림 > four 로 바꿔주셈
7. 점수표 선택에 대한 gui 가 어색함 ex) 1. Aces : 1 >> ① Aces : 1 이런 식이나 뭔가 표 숫자에 대한 가시성이 떨어짐
8. Count 1/3 , Turn 4/12 이런 녀석들 마지막 턴에 임박할 수록 색상이 변했으면 좋겠습니다 
ex) Count 첫 리롤은 초록 두번째 리롤은 파랑 세번째 리롤은 빨강, Turn 같은 경우 1~4 까진 초록 5 ~ 8까진 파랑 9 ~ 12 는 빨강 등

**Comment by kdelphinus** [comment]
1. 해결
2. 무슨 소리인지 더 자세하게 설명 필요
3. 이해는 가지만 구조를 갈아엎어야 해서 너무 큰 일
4. 굴리는 모션을 만들어주면 고려해봄
5. 화려한 문구가 떠오르지 않음
6. 해결
7. 해결
8. 귀찮

**Comment by AnnyangEH** [comment]
2. ex) 야추 나오면 YACHT! 라고 표시가 되는데, 그 점수가 등록된 후 야추가 또 나왔을 시에는 그냥 아무 표시 안되듯, 현재 화면에 표시되는 메세지를 출력 해달라는 뜻(스스, 라스, 야추, 풀하, 포오카) 같이 보너스 항목에 있는 친구들이 점수등록이 안되었을 때
3. 갈아 엎어주세요
5. 위너위너 치킨 디너..?
